## Scalars

In [15]:
import numpy as np

s = np.array(5)
print s
print s.shape  # return empty tuple
print type(s)
print s.dtype

5
()
<type 'numpy.ndarray'>
int64


## Vectors

In [16]:
v = np.array([1, 2, 3])
print v[1]
print v.shape
print type(v)   # return tuple of one element (for 1D)
print v.dtype

2
(3,)
<type 'numpy.ndarray'>
int64


## Matrices

In [17]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print m[0][2]
print m.shape
print type(m)
print m.dtype   # return tuple of two elements (2D)

3
(3, 3)
<type 'numpy.ndarray'>
int64


## Tensors

In [18]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print t[2][1][1][0]
print t.shape
print type(t)
print t.dtype

16
(3, 3, 2, 1)
<type 'numpy.ndarray'>
int64


## Vectorized Operations

In [2]:
import numpy as np

values = [1, 2, 3, 4, 5]
values = np.array(values) + 5
print values = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

[ 6  7  8  9 10]


In [3]:
a = np.array([[1, 3], [5, 7]])
b = np.array([[2, 4], [6, 8]])
print a
print b

print a + b

[[1 3]
 [5 7]]
[[2 4]
 [6 8]]
[[ 3  7]
 [11 15]]


In [4]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
print a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

## Matrix multiplication and matrix product

In [5]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
n = m * 0.25
n

array([[ 0.25,  0.5 ,  0.75],
       [ 1.  ,  1.25,  1.5 ]])

In [7]:
m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [9]:
print m.shape
print n.shape
np.matmul(m, n)

(2, 3)
(2, 3)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [10]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape

(2, 4)

In [11]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b.shape

(4, 3)

In [12]:
np.matmul(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

In [13]:
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

array([[ 70,  80,  90],
       [158, 184, 210]])

## Transpose

In [19]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])